# Generated by Django 5.0.7 on 2024-07-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='realname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
